FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json /usr/src/app

RUN npm install

WORKDIR /usr/src/app/src

EXPOSE 3000

CMD [ "node", "server.js" ]